name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Sync dependencies (dev)
        run: uv sync --dev

      - name: Lint (ruff)
        run: .venv/bin/ruff check .

      - name: Format check (black)
        run: .venv/bin/black --check .

      - name: Run tests
        run: .venv/bin/pytest -n auto -q

